<?php
/**
 * Created by PhpStorm.
 * User: shangning
 * Date: 2018/4/20
 * Time: 15:18
 */

namespace  Shangning\Yuntongxun\Facades;

use Illuminate\Support\Facades\Facade;

class Yuntongxun extends Facade {


    protected static function getFacadeAccessor()
    {
//        parent::getFacadeAccessor(); // TODO: Change the autogenerated stub
        return 'yuntongxun';
    }

}